"""Fix relationships and foreign keys

Revision ID: 52655eca11ee
Revises: 197ccd07511d
Create Date: 2024-12-21 18:58:42.612737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52655eca11ee'
down_revision = '197ccd07511d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('board_id', sa.Integer(), nullable=False))
        batch_op.alter_column('likes_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'board', ['board_id'], ['board_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('likes_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('board_id')

    # ### end Alembic commands ###
